const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = new Schema(
  {
    username: {
      type: String,
      required: true
    },
    password: {
      type: String,
      required: true
    },
    relative_path: String,
    isAutoGenerated: {
      type: Boolean,
      default: false
    }
  },
  {
    timestamps: true
  }
);

module.exports = mongoose.model('FtpAccount', schema);

