export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_FETCHED_ALL_USERS = "USER_FETCHED_ALL_USERS";

export const FETCHED_ALL_LOCATIONS = 'FETCHED_ALL_LOCATIONS';